name: nwhco_exam
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  get_it: ^7.6.4
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  shared_preferences: ^2.2.2
  injectable: ^2.3.2
  dio: ^5.3.3
  flutter_svg: ^2.0.9
  flutter_spinkit: ^5.2.0
  persistent_bottom_nav_bar: ^5.0.2
  material_design_icons_flutter: ^7.0.7296
  infinite_scroll_pagination: ^4.0.0
  cached_network_image: ^3.1.0
  http_parser: ^4.0.2
  path_provider: ^2.1.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  build_runner: ^2.4.6
  injectable_generator: ^2.4.1

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/svg/

  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/DMSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/DMSans-Light.ttf
          weight: 300
        - asset: assets/fonts/DMSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/DMSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/DMSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/DMSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/DMSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/DMSans-Black.ttf
          weight: 900
